#!/bin/sh

cd /jffs/send_packets

num_lines=$(wc -l < /jffs/log)
if [ $num_lines -ge 500 ]; then
        rm /jffs/log
fi

./reload.sh

./config.sh 0xf000 >/jffs/log_configuration

tag=$( tail -n 1 /jffs/log_configuration  )
if [[ "$tag" == "Read 476 bytes" ]]; then
        echo "Router channels configured successfully" >>/jffs/log
else
        echo "Router channels configuration failed. Requires restarting..." >>/jffs/log
	sleep 20
	service reboot
fi

acceptable_number="1200"
offence_count="1"
max_offence="3"
loop_count=1

while [ $loop_count -le 2000  ]
do
	temp=$(./transmit4ever80fastng.sh 4000) 
	
	t=${#temp}
	
	if [ $t -lt $acceptable_number ]; then
        	echo "Number of Packets not acceptable" >>/jffs/log
		((offence_count++))
	fi
	
	loop_count=$(( $loop_count + 1  ))
	if [ $offence_count -gt $max_offence ]; then
		echo "Maximum offence reached. Needs Restarting.">>/jffs/log
		sleep 10
		service reboot
	fi
	 
done

service reboot
